### ISSUE TITLE
Undefined syntax 'string' in RealTimeMessage and RealTimeNotification class

### ISSUE THREAD

**Issue by NasrinAfrozKakoli** [christophrumpel/blog-laravel-real-time-notifications#1]
### Undefined syntax 'string' in RealTimeMessage and RealTimeNotification class. 
The error was shown every time I tried to tinker the message. So, I removed the type  'string' from $message variable. And It worked perfectly. 

Both class were like this after editing, 
```
class RealTimeMessage implements ShouldBroadcast
{
    use SerializesModels;
    
    public $message;

    public function __construct($message)
    {
        $this->message = $message;
    }
```
and
```
class RealTimeNotification extends Notification implements ShouldBroadcast

{
    use Queueable;
    public $message;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($message)
    {
        $this->message = $message;
    }
```

You did an amazing job. Thank you so much for the easiest tutorial possible.

**Comment by hnnweb** [comment]
Use PHP 7.4 and "string" will work.

**Comment by christophrumpel** [comment]
Yeah @hnnweb is right, you need to have PHP 7.4+ to make it work properly, or remove the type hints as you did.
