### ISSUE TITLE
Avoid use of jobs DB table on Notifications [Question]

### ISSUE THREAD

**Issue by lucianobosco** [christophrumpel/blog-laravel-real-time-notifications#3]
Hi there! I found your tutorial a time ago and it was my guidance to implement WebSockets from that time until now.
**THANKS, A LOT!!!**.

Now I have a little question. when using Events for broadcasting you can "bypass" database queues by implementing `ShouldBroadcastNow`. That means that there is no need to keep the worker running.

Since my project is exponentially growing I've decided to move my broadcast Events as Notifications, but now I'm facing that all broadcast notifications depend on the jobs DB table, despite no `Queueable` trait is being used.
Are you aware if this can be avoided? I know that this is not a real issue, in fact, is a good idea to queue notifications just in case that dispatch fails, but I don't like the idea to have no control over this situation.

This is my Notification. Thanks in advance
```
<?php

namespace App\Notifications\Admin;

use App\Models\Room;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;
use Illuminate\Notifications\Messages\BroadcastMessage;

class RoomCreated extends Notification implements ShouldBroadcast
{
    protected Room $room;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct(Room $room)
    {
        $this->room = $room;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return ['broadcast'];
    }

    /**
     * Get the type of the notification being broadcast.
     *
     * @return string
     */
    public function broadcastType()
    {
        return 'room.created';
    }

    /**
     * Get the broadcastable representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return BroadcastMessage
     */
    public function toBroadcast($notifiable)
    {
        $patient = $this->room->patients()->first();

        $payload = [
            'id' => $this->room->id,
            'name' => $this->room->name,
            'sid' => $this->room->sid,
            'status_id' => $this->room->status_id,
            'patient' => [
                'doc_number' => $patient->doc_number,
                'sid' => $patient->sid,
                'installation_id' => $patient->installation_id,
                'name' => $patient->patient ? $patient->patient->full_name : null,
                'avatar' => $patient->patient && $patient->patient->avatar ? $patient->patient->avatar->url : null
            ]
        ];

        return new BroadcastMessage(['data' => $payload]);
    }
}
```

**Comment by lucianobosco** [comment]
After some research, I found that by default, all broadcast notifications are queued for broadcasting. Therefore, and following your sample, it can be achieved by defining the connection in `toBroadcast()` method:

```
public function toBroadcast($notifiable): BroadcastMessage
{
        return (new BroadcastMessage([
            'message' => "$this->message (User $notifiable->id)"
        ]))->onConnection('sync');
 }
```

**Comment by christophrumpel** [comment]
Hey, glad you like the article. Does this mean you found what you were looking for?

**Comment by lucianobosco** [comment]
Yes, exactly! If you want to avoid queues when using broadcast notifications you just need to add `->onConnection('sync')`. That will trigger notifications immediately without using the database jobs table, at least in Laravel 8.
So feel free to close this "issue".

**Comment by christophrumpel** [comment]
Cool, thanks a lot! I might add that to the article, so thanks for sharing. 👍
